# Generated by Django 5.0.6 on 2024-07-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_alter_artisanprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='is_artisan',
            field=models.BooleanField(default=True),
        ),
    ]
