# Generated by Django 5.0.6 on 2024-07-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_artisanprofile_is_artisan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='is_artisan',
        ),
        migrations.AddField(
            model_name='professionalqualifications',
            name='file_description',
            field=models.CharField(default='My Dummy Qualification File', max_length=100),
            preserve_default=False,
        ),
    ]
